# Generated by Django 4.0.4 on 2022-05-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal_name', models.CharField(max_length=200)),
                ('criminal_age', models.PositiveIntegerField()),
                ('criminal_image', models.CharField(max_length=500)),
            ],
        ),
    ]
