# Generated by Django 4.0.4 on 2022-05-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminaldetail',
            name='criminal_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='criminaldetail',
            name='criminal_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='criminaldetail',
            name='criminal_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
