# Generated by Django 4.0.4 on 2022-05-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_detection', '0003_criminaldetail_crime_committed_criminaldetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminaldetail',
            name='encodings',
            field=models.CharField(default='none', max_length=2000),
            preserve_default=False,
        ),
    ]
