# Generated by Django 4.0.4 on 2022-05-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_detection', '0005_alter_criminaldetail_encodings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminaldetail',
            name='criminal_age',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
    ]
