# Generated by Django 4.0.4 on 2022-05-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_detection', '0007_alter_criminaldetail_criminal_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminaldetail',
            name='criminal_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
