# Generated by Django 4.0.4 on 2022-05-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_detection', '0009_alter_criminaldetail_criminal_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminaldetail',
            name='criminal_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
