# Generated by Django 4.0.4 on 2022-05-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_detection', '0010_alter_criminaldetail_criminal_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_image', models.CharField(max_length=500)),
                ('test_encodings', models.CharField(blank=True, max_length=6000, null=True)),
            ],
        ),
    ]
