# Generated by Django 4.0.4 on 2022-05-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_detection', '0011_imagematchdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminaldetail',
            name='criminal_image',
            field=models.ImageField(default='', upload_to='Images'),
        ),
    ]
