# Generated by Django 4.0.4 on 2022-05-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_detection', '0012_alter_criminaldetail_criminal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagematchdetail',
            name='test_image',
            field=models.ImageField(default='', upload_to='Test_Image'),
        ),
    ]
