# Generated by Django 4.0.4 on 2022-05-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_detection', '0013_alter_imagematchdetail_test_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagematchdetail',
            name='temp_integer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
